version: '3'
services:
  api:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
    - DB_URI=mongodb://db:27017/test
    - DB_NAME=test
    - SECRET=secret
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon app.js --config nodemon.json
  db:
    image: mongo
    ports:
    - "27017:27017"
